### ISSUE TITLE
Config.yml Toggles Don't work.

### ISSUE THREAD

**Issue by EnderGamingFilms** [TownyAdvanced/TownyFlight#11]
### What is the issue that you see?
Config.yml Toggles Don't work.
### What steps can be done to repeat the issue on a test server?
1. install latest version
### What is supposed to happen instead?
1. disable the permission note in the error message
2. hide the auto enable/disable message

### Versions/Files

Towny Version (use '/towny v' in game) : 0.93.0.0
TownyFlight Version : 1.2.5
Link to pastebin.com with TownyFlight config.yml : https://pastebin.com/sqj7K20d

**Comment by LlmDl** [comment]
Can you show me a screenshot of what it does show please.

**Comment by EnderGamingFilms** [comment]
https://imgur.com/EtvHiUy.png

**Comment by LlmDl** [comment]
This ought to fix it: https://www.spigotmc.org/resources/townyflight.50360/update?update=282476
