### ISSUE TITLE
Showing reload permission node for no reason

### ISSUE THREAD

**Issue by JohnS19** [TownyAdvanced/TownyFlight#12]
### What is the issue that you see?
Configuration option "options.show_Permission_After_No_Permission_Message" does not work.
Enabling this replaces the permission node to the reload node for some odd reason; does not remove nodes when no permission.

### What steps can be done to repeat the issue on a test server?
1. Use the townyflight command(to fly) without permission

### What is supposed to happen instead?
1. Simple say, "you do not have permission for this command"

### Versions/Files

Towny Version (use '/towny v' in game) : 0.93.1.0 Pre Release 4
TownyFlight Version : 1.2.6

![image](https://user-images.githubusercontent.com/48459351/61096324-f562d000-a40b-11e9-9002-4354bcad5d8e.png)

**Comment by LlmDl** [comment]
Please try out this version: https://www.dropbox.com/s/wg597qlncxqol3q/TownyFlight-1.2.7.jar?dl=0

**Comment by JohnS19** [comment]
Fixed, thank you.
