### ISSUE TITLE
Suggestion: Flight in all towns

### ISSUE THREAD

**Issue by LazyFrog19** [TownyAdvanced/TownyFlight#14]
Can we have a configurable option and permission to allow townflight in all town claims?

**Comment by LlmDl** [comment]
Flight in all towns but no flight in the wilderness still?

**Comment by LazyFrog19** [comment]
Yes

**Comment by LlmDl** [comment]
Ok: https://github.com/TownyAdvanced/TownyFlight/releases/tag/1.5.0

Make sure you're on Towny 0.94.0.2+ and use MC 1.14
