### ISSUE TITLE
Command return false message

### ISSUE THREAD

**Issue by Arkobat** [TownyAdvanced/TownyFlight#17]
When using /tfly, the command is sent to the player (return false; in command handler)
It happens when the player
- Doesn't have permission
- Isn't in their own own

I've created a pull request with some small fixes :)
https://github.com/TownyAdvanced/TownyFlight/pull/16

**Comment by LlmDl** [comment]
Gotten this worked into 1.5.2, I think I must have had them set to false while I was exploring whether I should use the plugin.yml's permission system for commands. Thanks for spotting it.
