### ISSUE TITLE
(v1.5.5) `config.yml` uses strings for booleans

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/TownyFlight#24]
The boolean fields in the `options` section of `config.yml` are quoted.  They should be unquoted so that they can be read directly as booleans, since strings are comparatively expensive.

**Comment by MilesBHuff** [comment]
This one is really easy for me to just fix and PR, but I don't like making PRs without testing first.  What I can say, though, is that the config file works when I remove the quotes, so it should be very safe to make this change.  Even if Java ends-up parsing them as strings, anyway, at least we've saved a couple characters in the config file.

**Comment by LlmDl** [comment]
yeah I dont care enough about whether it's true or 'true' either.

**Comment by MilesBHuff** [comment]
Haha, no worries.  Worth mentioning, was all.
