### ISSUE TITLE
Support for colour codes in the language section of the config.

### ISSUE THREAD

**Issue by PeterDorvay** [TownyAdvanced/TownyFlight#26]
### What is the issue that you see?
No support for colour codes in the config!

Link to pastebin.com with TownyFlight config.yml :

  # Message shown when a player lacks a permission node.
  noPermission: '&7You can purchase this command at &c/warp commands!'

**Comment by MilesBHuff** [comment]
There's actually always been support for colors in the config!  You just had to use '§'.  There was a major bug with it, though:  Towny would remove all '§' characters each time it ran, so you had to use version control (like git) and checkout the file after each run.
