### ISSUE TITLE
BUG: tfly will not disable properly when town is deleted

### ISSUE THREAD

**Issue by yumjunstar** [TownyAdvanced/TownyFlight#27]
### What steps can be done to repeat the issue on a test server?
1. make a town
2. /tfly
3. ./town delete

### What is supposed to happen instead?
1. town flight is removed

### Versions/Files

Towny Version (use '/towny v' in game) : 0.95.2.22
TownyFlight Version :1.5.6
Link to pastebin.com with full server startup from the latest.log : I found no error about towny flight on startup
Link to pastebin.com with TownyFlight config.yml :
https://paste.gg/p/anonymous/67d12a91dca049d9991fcf7c94bb8b84

**Comment by LlmDl** [comment]
I believe someone else posted about this but I could not reproduce it. /t delete still fires townunclaimevents, which TownyFlight does listen to in order to remove flight from people.

**Comment by LlmDl** [comment]
I'm pretty sure you mean to say 1. town flight is removed.

**Comment by yumjunstar** [comment]
@LlmDl That's my mistake Maybe, It could happen because of server lagg

**Comment by LlmDl** [comment]
I'll still check it out when I get the chance.

**Comment by LlmDl** [comment]
Couldn't get this one to happen. Please re-file if it as issue and you find it is reproduce-able.
