### ISSUE TITLE
Bug: Double-Quoted Strings get reduced to Single-Quoted Strings in Config

### ISSUE THREAD

**Issue by UberPilot** [TownyAdvanced/TownyFlight#28]
### What steps can be done to repeat the issue on a test server?
1. Install Towny and TownyFlight.
2. Set `pluginPrefix: "&3Towny &7\u00bb &f"`
3. Reload the plugin or restart the server.
4. Notice the new prefix, displaying the unicode right-pointing double angle quotation mark in the prefix.
4. `pluginPrefix` will turn into `pluginPrefix: '&3Towny &7� &f'` in the config, with � being the replacement (0xFFFD) character.
5. Reload the plugin or restart the server again.
6. Notice the new prefix, displaying the unicode replacement character.

### What is supposed to happen instead?
1. `pluginPrefix` should remain double-quoted and display unicode characters.

### Versions/Files

Towny Version (use '/towny v' in game): 0.96.0.1
TownyFlight Version: 1.5.7
Link to TownyFlight config.yml (errored): https://pastebin.com/4j9SFNmY
Link to TownyFlight config.yml (ideal): https://pastebin.com/sii2Sw9w

**Comment by LlmDl** [comment]
Does it do anything differently when you use the » instead of \u00bb in the file?

**Comment by UberPilot** [comment]
No, it doesn't. It still gets replaced to the same string from step 5 above.

**Comment by UberPilot** [comment]
Turns out that this was a pretty trivial fix. I've created a pull request that will solve this.

**Comment by LlmDl** [comment]
Looks like we went to take care of this act pretty much the exact same time. Thanks though.
