### ISSUE TITLE
TownyFlight Not Working Properly

### ISSUE THREAD

**Issue by FrozenWhispers** [TownyAdvanced/TownyFlight#3]
### What is the issue that you see?
TownyFlight doesn't activate and deactivate at the correct times.  It doesn't register when you leave town, but it does when you enter town. So if I leave town it stays active, then I go back to town and it deactivates, then it stays deactivated when I leave, and turns on when I come back.

### What steps can be done to repeat the issue on a test server?
1. Create a towny town.
2. Set TownyFlight to auto-enable when entering town.
3. Fly in and out of town to see it activate and deactivate at the wrong times

### What is supposed to happen instead?
1. It's supposed to activate when you enter town and deactivate when you leave town.
2.
3.

### Versions/Files

Towny Version (use '/towny v' in game) : 0.92.0.0 (for MC 1.8.5)
TownyFlight Version : 1.2.2
Link to pastebin.com with full server startup from the latest.log : https://pastebin.com/WjDNkmGk
Link to pastebin.com with TownyFlight config.yml : https://pastebin.com/j7yXNWDy

**Comment by LlmDl** [comment]
Update to at least [towny 0.92.0.1](http://towny.palmergames.com/dev-build-towny-advanced-0-92-0-1-1-11-2/) and stop using 0.92.0.0 (for MC 1.8.5) you don't have MC 1.8.5.
