### ISSUE TITLE
TownFlight gets disabled when travelling between nation towns

### ISSUE THREAD

**Issue by bartyrealms** [TownyAdvanced/TownyFlight#30]
### What is the issue that you see?
TownFlight is getting disabled when flying through areas you have permission to fly in, it should stay enabled until you enter a non-allied town or the wilderness.
### What steps can be done to repeat the issue on a test server?
1. Place two towns next to each other.
2. Create a nation 
3. Turn on /tfly, try to fly to the other town.
4. Flight is disabled
### What is supposed to happen instead?
1. Place two towns next to each other.
2. Create a nation 
3. Turn on /tfly, try to fly to the other town.
4. Flight is still enabled

### Versions/Files

Towny Version (use '/towny v' in game) : 0.96.0.2
TownyFlight Version : 1.5.8
Link to pastebin.com with full server startup from the latest.log : Irrelevant, no errors.
Link to pastebin.com with TownyFlight config.yml : https://paste.gg/p/anonymous/7195a3b519014ead8cfaaf0c2ea865ea

**Comment by LlmDl** [comment]
what townyflight permissions have you given?
