### ISSUE TITLE
Feature Request: Fly in Vanish

### ISSUE THREAD

**Issue by ReMank0** [TownyAdvanced/TownyFlight#32]
### What is the issue that you see?

I was hoping see if it was possible add this feature. to  keep players flight enable no matter what if they are in vanish.

### What steps can be done to repeat the issue on a test server?
1. essentials /vanish
2. hit player
3. flight disabled

### What is supposed to happen instead?
1. essentials /vanish
2. hit player
3. keep flight

**Comment by LlmDl** [comment]
But you want non-vanished players to still have their flight taken away when they start doing combat?

I am planning to implement this: https://github.com/TownyAdvanced/TownyFlight/issues/31 in the near future. Does spectator gamemode not work better than essentials vanish?

**Comment by Nextopi** [comment]
yes non-vanished players will have they flight taken away but vanished players not.

Spectator works better but not every staff from my server has access to it.

vanish in my server is a command used mostly to spy on people that are probably hacking so.
