### ISSUE TITLE
TownyFlight Repeats the /tfly after leaving your town if the config is reloaded

### ISSUE THREAD

**Issue by Micim987** [TownyAdvanced/TownyFlight#36]
### What is the issue that you see?
After reloading the config for TownyFlight the function that disabled the /tfly command runs multiple times equal to the number of reloads + 1. i.e. reload config once and flight is disabled and then enabled when a player leaves their town
### What steps can be done to repeat the issue on a test server?
1. Reload the config
2. enable /tfly in your town
3. Leave your town then return
4. /tfly will disable then re-enable automatically

### What is supposed to happen instead?
1. Player enables /tfly
2. Player leaves town and /tfly is disabled without it being re-enabled automatically

### Versions/Files

Towny Version (use '/towny v' in game) :
TownyFlight Version : 1.6.0 
Towny Version: 0.96.1.11
Link to pastebin.com with full server startup from the latest.log : https://pastebin.com/CA53Rsbt
Link to pastebin.com with TownyFlight config.yml : https://pastebin.com/fZJ7pNf5

**Comment by LlmDl** [comment]
I would appreciate if you could test this for me: https://cdn.discordapp.com/attachments/581163022874050569/716733956200071168/TownyFlight-1.6.1.jar

**Comment by Micim987** [comment]
That new version worked. Reloading the config multiple times both with and without editing it resulted in /tfly only being toggled once fixing the issue.
