### ISSUE TITLE
Flight enabled in other towns after using /spawn

### ISSUE THREAD

**Issue by PeterDorvay** [TownyAdvanced/TownyFlight#38]
### What is the issue that you see?
If people are in their town with flight enabled, and then they do /spawn, then they /tp to someone who's in another town, towny flight stays on and they can fly in other towns.

This ONLY works if you first do /spawn. If you just enable fly in your town, and then /tp to someone who's in another town, towny flight will disable.

### What steps can be done to repeat the issue on a test server?
1. Create two towns
2. Go to your town and enable flight /tfly
3. Go to the server spawn /spawn
4. Teleport to another player who's in another town
5. You'll now be able to fly in their town

### What is supposed to happen instead?
1. Enable flight in your town
2. Go to server spawn with /spawn
3. Teleport to another player who's in their town
4. Don't have flight enabled in their town

### Versions/Files

Towny Version (use '/towny v' in game) : 0.96.1.11
TownyFlight Version : 1.6.1
Link to pastebin.com with full server startup from the latest.log : https://pastebin.com/7xsrLKKD
Link to pastebin.com with TownyFlight config.yml : https://pastebin.com/v9NKyQ7p

**Comment by LlmDl** [comment]
Which plugin is giving /spawn ?

**Comment by PeterDorvay** [comment]
EssentialsX version 2.17.0
