### ISSUE TITLE
Plugin Disabled On Startup

### ISSUE THREAD

**Issue by EnderGamingFilms** [TownyAdvanced/TownyFlight#40]
### What is the issue that you see?
TownyFlight is disabled at startup. I'm not sure how to fix this error. (See pastebin) It's a class not found error.

### Versions/Files
Towny Version (use '/towny v' in game): 0.96.2.0
TownyFlight Version: 1.6.2
Link to pastebin.com with full server startup from the latest.log :
https://pastebin.com/hf4uMbuv
Link to pastebin.com with TownyFlight config.yml :
https://pastebin.com/Xszc6MQy

**Comment by LlmDl** [comment]
1.6.2 requires a newer Towny version than you have, use https://github.com/TownyAdvanced/TownyFlight/releases/tag/1.6.1
