### ISSUE TITLE
Fly not disabled on /t unclaim

### ISSUE THREAD

**Issue by BetaBurnt** [TownyAdvanced/TownyFlight#41]
### What is the issue that you see?

If you have /tfly on and unclaim the land you're in your flight isn't disabled and you're able to fly around in the wilderness until you re-enter and then leave town land.

### What steps can be done to repeat the issue on a test server?
1. Claim a town and some chunks
2. Toggle your /tfly on
3. Unclaim the land you're on.

### What is supposed to happen instead?
/tfly should toggle off if the land you're on is unclaimed, same as when you leave your town land.

### Versions/Files

Towny Version (use '/towny v' in game) : 0.96.2.19
TownyFlight Version : 1.6.3
Link to pastebin.com with full server startup from the latest.log :  https://hastebin.com/epoyiyosab.sql
Link to pastebin.com with TownyFlight config.yml : https://hastebin.com/gesedodeju.yaml

**Comment by LlmDl** [comment]
Neither link to hastebin is working. Can you repost them?

**Comment by BetaBurnt** [comment]
Ah pastebin is back up I'll use that:
Log - https://pastebin.com/iS5nBaRc
config.yml - https://pastebin.com/h0NQErXK

Neither are likely to be particularly useful, it's just something the plugin does not appear to take into account with flight toggling

**Comment by LlmDl** [comment]
It does not happen on my test server using a default config or using your config. 

TownyFlight listens for Towny firing the unclaim event and then figures out which players are in the chunk that was unclaimed. 

Are there any other tricks to getting this to work all of the time?

**Comment by BetaBurnt** [comment]
I've asked players to let me know when it happens and if anything else is being done/is happening at the time so I can look into it further - has been reported by multiple players now though

**Comment by BetaBurnt** [comment]
Have not had any further reports of the issue since I opened this ticket so I have no idea what caused it - it was reported by multiple people across different towns over a few days and (of course) when I actually report it it stops happening :L
If it happens again I'll reopen the issue but for now I'll close this.
