### ISSUE TITLE
Deprecated Event WARN

### ISSUE THREAD

**Issue by trevor1097** [TownyAdvanced/TownyFlight#43]
### What is the issue that you see?

WARN "TownyFlight v1.6.3" has registered a listener for com.palmergames.bukkit.towny.event.TownUnclaimEvent on method "private void com.gmail.llmdlio.townyflight.listeners.TownUnclaimListener.TownUnclaimEvent(com.palmergames.bukkit.towny.event.TownUnclaimEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [LlmDl].

### What steps can be done to repeat the issue on a test server?
1.Start Server

### Versions/Files

Towny Version (use '/towny v' in game) : 96.5.6
TownyFlight Version : 1.6.3

**Comment by LlmDl** [comment]
this is something that will be fixed when we have the next towny release, thanks for the heads up though.
