### ISSUE TITLE
Unlimited fly after unclaiming edge territories

### ISSUE THREAD

**Issue by mokdennie26** [TownyAdvanced/TownyFlight#44]
### What steps can be done to repeat the issue on a test server?
1. Use /tfly in your own territory and fly to the edge of your territory.
2. Unclaim one or some of your edge territories.
3. The fly will not be disabled and then you can teleport to somewhere else in the map using /spawn or /warp and you will notice the unlimited fly in the unclaimed territory (wilderness).

### What is supposed to happen instead?
1. When the territory is unclaimed, the fly should be disabled.
2. The tfly should not work in wilderness.

### Versions/Files

Towny Version (use '/towny v' in game) : 0.96.5.13
TownyFlight Version: 1.6.4
Link to pastebin.com with TownyFlight config.yml : using the default config

**Comment by LlmDl** [comment]
I am not able to reproduce this in survival mode. Any more hints?

**Comment by mokdennie26** [comment]
hmm, I am also the one who is informed with this problem haha. At the moment, I am still asking for a video from players. But maybe the one who opened Issue#45 can help. Sorry for bothering.

**Comment by LlmDl** [comment]
https://cdn.discordapp.com/attachments/669247087329673228/806155461807570974/TownyFlight-1.6.6.jar

If you can please test this jar out for me, I believe it will solve this issue.
