### ISSUE TITLE
Unlimited Flight after Town Deletion

### ISSUE THREAD

**Issue by benben28405678** [TownyAdvanced/TownyFlight#45]
### What is the issue that you see?
After a town falls into ruin (or is deleted), flight is enabled for a user until they relog.

### What steps can be done to repeat the issue on a test server?
1. Ensure you are not opped.
2. Create a town
3. Enable /tfly
4. Delete the town
5. Flying should still be enabled

### What is supposed to happen instead?
1. Ensure you are not opped.
2. Create a town
3. Enable /fly
4. Delete the town
5. Flight will stop

### Versions/Files

Towny Version (use '/towny v' in game) : 0.96.7.0
TownyFlight Version : 1.6.4
Link to pastebin.com with full server startup from the latest.log : https://pastebin.com/bqXwydeH
Link to pastebin.com with TownyFlight config.yml : https://pastebin.com/WnpBA9c0

**Comment by LlmDl** [comment]
I'll check this out, but it might also be like #44 which I cannot reproduce.

**Comment by benben28405678** [comment]
Alright, I checked out #44 too so I guess we'll see what happens.

You do amazing work by the way; huge fan.

**Comment by LlmDl** [comment]
https://cdn.discordapp.com/attachments/669247087329673228/806155461807570974/TownyFlight-1.6.6.jar

If you can please test this jar out for me, I believe it will solve this issue.

**Comment by benben28405678** [comment]
> https://cdn.discordapp.com/attachments/669247087329673228/806155461807570974/TownyFlight-1.6.6.jar
> 
> 
> 
> If you can please test this jar out for me, I believe it will solve this issue.

I'll check it out and run it first thing in the morning.

Thanks for putting the jar together.

**Comment by benben28405678** [comment]
It works perfectly. After I delete the town, I can no longer fly.

Thanks so much!
