### ISSUE TITLE
Players are able to fly in the wild if they unclaim while using tfly

### ISSUE THREAD

**Issue by JustAMatt** [TownyAdvanced/TownyFlight#46]
### What is the issue that you see?

A player can keep their fly ability if they unclaim a border chunk while flying on it with the permission tfly.owntown. They won't loss fly in the wild until they return to a plot claimed by their town. 

### What steps can be done to repeat the issue on a test server?
1. Have tfly on your own town.
2. Go to a border chunk while flying.
3. Unclaim the chunk and fly straight to the wild.
4. profit

### What is supposed to happen instead?
1. Player unclaims chunk.
2. They lose flight and fall to the ground.

### Versions/Files

Towny Version (use '/towny v' in game) : 0.96.7.0
TownyFlight Version : TownyFlight-1.6.5
Link to pastebin.com with full server startup from the latest.log : https://pastebin.com/CKMLQ7VL
Link to pastebin.com with TownyFlight config.yml : https://pastebin.com/5ByaTVsb

**Comment by LlmDl** [comment]
Already fixed: https://github.com/TownyAdvanced/TownyFlight/releases/tag/1.6.6
