### ISSUE TITLE
/tfly does not deactivate when you fly out of bounds of your town

### ISSUE THREAD

**Issue by Luberr-Dhruv** [TownyAdvanced/TownyFlight#48]
### What is the issue that you see?
/tfly works like /fly and does not deactivate when you fly out of the town claimed chunks

### What steps can be done to repeat the issue on a test server?
1. use paper 1.16.5
2. make a test town and de op your self.
3. initiate tfly inside your town and fly out of the claimed chunk,

### What is supposed to happen instead?
1. the tfly should follow the stuff in the config files to properly deactivate after the return timer
2. -
3. -

### Versions/Files

Towny Version (use '/towny v' in game) : 0.96.7.0
TownyFlight Version : 1.6.6
Link to pastebin.com with full server startup from the latest.log : https://pastebin.com/akeyQABc
Link to pastebin.com with TownyFlight config.yml : https://pastebin.com/xQ8mHPNi

**Comment by LlmDl** [comment]
Possible duplicate of https://github.com/TownyAdvanced/TownyFlight/issues/46

I have been unable to reproduce this behaviour. The above ticket required the player to unclaim the plot but your instructions say to just fly outside.

On my tests I have flight removed in both situations. My guess would be that you have given yourself the bypass permission node.

**Comment by Luberr-Dhruv** [comment]
I tried the 1.6.1 version which works flawlessly. I will retry the 1.6.6 version and update it. Thank you for the quick reply. :D

**Comment by Luberr-Dhruv** [comment]
Ok, I tried 1.6.6 again and now it works. I must have wrongly configured the permissions on my end. I apologize for the inconvenience. I hope a good review on SpigotMC would suffice ;p. Thankyou!

**Comment by LlmDl** [comment]
Have fun.
