### ISSUE TITLE
Conflict between fly plugins

### ISSUE THREAD

**Issue by Bibithom** [TownyAdvanced/TownyFlight#49]
### What is the issue that you see?
Conflict with other fly plugin, fly from other source than townyflight is threated as TownyFlight Fly while going outside of town boundaries. So "permanent fly" is disabled by townyflight but it won't cause it is expected to be independant from towns
Is there a way to identify difference between townyflight and other flight ?

### What steps can be done to repeat the issue on a test server?
1. Have a fly plugin (in this case essentialx). Activate flight inside town, (/fly)
2. Go out of bound of town, fly disabled itself.

### What is supposed to happen instead?
1. Activating fly
2. Going outside of town
3. fly still be activated.

### Versions/Files

Towny Version (use '/towny v' in game) : **0.96.7.11**
TownyFlight Version : **1.6.7**
Link to pastebin.com with full server startup from the latest.log : https://pastebin.com/Rf4aMKx3
Link to pastebin.com with TownyFlight config.yml : https://pastebin.com/NEL06uQD
Tested with EssentialX (2.18.2.0) and CMI (8.8.2.10)

Have a nice day, thank's for your support.

**Comment by LlmDl** [comment]
If you have players that should be able to bypass Towny boundaries and fly you should be giving those players the `townyflight.bypass` permission node.

**Comment by Bibithom** [comment]
Ok thank you have a nice day
