### ISSUE TITLE
plugin does not work

### ISSUE THREAD

**Issue by JustinDevB** [TownyAdvanced/TownyFlight#52]
### What is the issue that you see?
/tfly does not let someone fly, even an operator. Just says temporary fly mode is not enabled for player.
for non opped players who have the permission townyflight.command.tfly are told that they do not have permission to use that command
### What steps can be done to repeat the issue on a test server?
1. install plugin
2. /tfly as an opped player
3.

### What is supposed to happen instead?
1. player is supposed to fly in their town
2.
3.

### Versions/Files

Towny Version (use '/towny v' in game) : 0.96.7.15
TownyFlight Version : 1.6.7
Link to pastebin.com with full server startup from the latest.log :
Link to pastebin.com with TownyFlight config.yml :

**Comment by LlmDl** [comment]
Sounds like you have a plugin that adds a temporary flight using the /tfly command. Remove that plugin and you will find /tfly works using TownyFlight. Also update your Towny to 0.97.0.0 ASAP.

**Comment by JustinDevB** [comment]
Looks like /townyflight works, but just not /tfly
