### ISSUE TITLE
Disable permission name in noPerm msg

### ISSUE THREAD

**Issue by Arkobat** [TownyAdvanced/TownyFlight#6]
### What steps can be done to repeat the issue on a test server?
Install tonwy flight
Enable fly without permission

### What is supposed to happen instead?
The perm shouldn't show (Or an option to disable it)

### Versions/Files

Towny Version (use '/towny v' in game) : 0.93.0.0
TownyFlight Version : 1.2.3
Link to pastebin.com with full server startup from the latest.log : Not necessary, as it isn't a bug, but a suggestion.
Link to pastebin.com with TownyFlight config.yml : http://hatebin.com/hilvermwki

**Comment by LlmDl** [comment]
https://github.com/TownyAdvanced/TownyFlight/pull/10

**Comment by LlmDl** [comment]
Fixed as of 1.2.5
