### ISSUE TITLE
Fly deactivates on town exit when the player has global access to /fly

### ISSUE THREAD

**Issue by Rubyo2000** [TownyAdvanced/TownyFlight#63]
Hi there, 
I'm Rubyo, Admin on a Towny server and I've come an issue regarding Towny Flight. 

We've recently launched a new server in our series of Towny Servers and implemented Towny Flight for the first time. We've been enjoying the plugin and the use for it, however we've also come across a big issue. When players fly in their town, and then leave their claims, after a short delay fly gets removed (as it should). The problem we're having is that when a player has the permission for global /fly, Towny Flight still disables their flight upon exiting their town, even though they have permission to continue on flying through the whole world. This is not enjoyable for anyone, which is why I've come to you to ask if you would be able to fix this issue.

### What steps can be done to repeat the issue on a test server?
1. Give the player both 'townyflight.command.tfly' & 'essentials.fly'.
2. Fly in your town using /fly.
3. Exit your claims. 

### What is supposed to happen instead?
1. Fly should be disabled when the player leaves their claims and does not have fly perms outside.

### Versions/Files

Towny Version : 0.98.2.0
TownyFlight Version : 1.8.4
Server version: Paper 1.18.2-379
To give players flying permissions, we use EssentialsX-2.19.4

Thank you very much for your time and effort. (I can imagine you're quite busy being the head dev of a big plugin as Towny is :D)

Hope to hear from you soon,
Rubyo

**Comment by LlmDl** [comment]
TownyFlight just modifies the player's getAllowedFlight(), turning it off when they exit. Its not intended to be used in conjunction with another flight system. Your admins can get the bypass node.

**Comment by LlmDl** [comment]
I guess anyone that is given the essentials flight node can also have the townyflight bypass node and they wont lose their flight. They will be able to fly in towns they shouldn't be able to otherwise though.

**Comment by Rubyo2000** [comment]
Thank you for your quick reaction! I've added the bypass permission node to the fly package and it seems to work as intended :)
