### ISSUE TITLE
Feature Request | townyflight.trustedtowns

### ISSUE THREAD

**Issue by EcoSMP** [TownyAdvanced/TownyFlight#65]
At the moment there are permissions to allow players in the same nation, allied towns/nations, or fly in all towns:

- townyflight.nationtowns
- townyflight.alliedtowns
- townyflight.alltowns

We would like to have another permission added to allow players that are trusted in a town/plot to fly there:

- townyflight.trustedtowns

Thank you for your consideration!

**Comment by LlmDl** [comment]
https://github.com/TownyAdvanced/TownyFlight/releases/tag/1.8.5

**Comment by LlmDl** [comment]
That might be possible yes, it requires listening to a different event.
