### ISSUE TITLE
Flight auto-enable / disable dysfunctional

### ISSUE THREAD

**Issue by OpalMoonstride** [TownyAdvanced/TownyFlight#7]
### What is the issue that you see?
Flight activation / deactivation dysfunctional.
### What steps can be done to repeat the issue on a test server?
1. Enter town - receive flight activation. 
2. Exit town (wilderness) - flight is not deactivated.
3. Enter town - flight deactivated.
4. Exit town. - flight remains deactivated.
5. Re-enter town - flight activated again.

### What is supposed to happen instead?
1. Enter town - flight activated.
2. Exit town - flight deactivated.

### Versions/Files

Towny Version (use '/towny v' in game) : 0.93.0.0
TownyFlight Version : 1,2,3
Link to pastebin.com with full server startup from the latest.log :  https://paste.ubuntu.com/p/qvffqVc2KN/
Link to pastebin.com with TownyFlight config.yml : https://pastebin.com/sPJhc00t

**Comment by LlmDl** [comment]
Got to this too late and the pastes don't exist anymore. Does this still happen if you test it again?

**Comment by OneCake** [comment]
I can confirm that this is still an issue

**Comment by OneCake** [comment]
there are no errors on load and no notations or errors in the log when you enter and leave a town

**Comment by LlmDl** [comment]
@OneCake file a new ticket with all of the form filled in.
