### ISSUE TITLE
When you leave town, flight remain

### ISSUE THREAD

**Issue by w1th0utme** [TownyAdvanced/TownyFlight#77]
When you leave town, flight remain

### What steps can be done to repeat the issue on a test server?
1. Be on town property and have permission to flight
2. Activate flight, fly up and leave town
3. Flight remain

### Versions/Files

Towny Version (use '/towny v' in game): 0.100.2.3
TownyFlight Version : 1.10.1

**Comment by LlmDl** [comment]
Do the normal Towny chunk notifications appear on your server?

**Comment by w1th0utme** [comment]
> Do the normal Towny chunk notifications appear on your server?

I'm a little confused about your question. I can say that when I fly out of town after that, the flight stops and I can no longer fly.

**Comment by LlmDl** [comment]
It sort of sounds like your server doesn't throw the normal player-changes-plot event, but then it does throw it, but only some of the time. If you don't see the `~ Wilderness` chunk notification when you leave town, that would be indicative that the events towny and towny flight uses weren't thrown or detected.

**Comment by w1th0utme** [comment]
Apparently I misspoke and you misunderstood me. I meant to leave town using the /t leave command
