### ISSUE TITLE
Flight disabled upon entering town

### ISSUE THREAD

**Issue by OneCake** [TownyAdvanced/TownyFlight#9]
**What is the issue that you see?**
Flight activation / deactivation dysfunctional.

**What steps can be done to repeat the issue on a test server?**
Staff (with override perms) Enter town in fly mode - flight is deactivated.
Exit town (wilderness) - flight still deactive
Enter town - flight reactivated.
**What is supposed to happen instead?**
Enter town - flight remain activated.

Versions/Files
Towny Version (use '/towny v' in game) : 0.93.0.0
TownyFlight Version : 1,2,4
Link to pastebin.com with full server startup from the latest.log : https://pastebin.com/MshiJeR6 
Link to pastebin.com with TownyFlight config.yml : https://pastebin.com/uafKLn7K

**Comment by diamondwelsh** [comment]
I've submitted a pull request to fix this, keep your finger crossed!

**Comment by LlmDl** [comment]
Added as of 1.2.5
